# This is a basic tutorial or using investpy package to collect data

## What is investpy?
investpy is the python api for the website "investing.com"

## Documentation
[HERE](https://investpy.readthedocs.io/_info/usage.html)

## Installation
```
pip install investpy

or 

pip3 install investpy
```

## Import

In [1]:
import investpy as iv
from datetime import date

## Get data for anything with an offical ticker  (stocks, etfs etc.)

In [2]:
df = iv.get_stock_historical_data(stock='AAPL',
                                        country='United States',
                                        from_date='01/01/2010',
                                       to_date='01/01/2020')

# first few lines, default 5
print("First few lines:\n")
print(df.head())

# last few lines, default 5
print("\nLast few lines:\n")
print(df.tail())

# summary statistics
print("\nSummary statistics:\n")
print(df.describe())

# getting the shape of the DataFrame

shape = df.shape
print(f'{shape=}')

# get the null/NaN values in each column of the dataframe
print("\nNull data:\n")
no_data = df.isna().sum()
print(no_data)

First few lines:

            Open  High   Low  Close     Volume Currency
Date
2010-01-04  7.62  7.66  7.58   7.64  493728704      USD
2010-01-05  7.66  7.70  7.62   7.66  601904640      USD
2010-01-06  7.66  7.69  7.53   7.53  552158912      USD
2010-01-07  7.56  7.57  7.47   7.52  477129760      USD
2010-01-08  7.51  7.57  7.47   7.57  447876768      USD

Last few lines:

             Open   High    Low  Close     Volume Currency
Date
2019-12-24  71.17  71.22  70.73  71.07   48479000      USD
2019-12-26  71.21  72.50  71.18  72.48   93336000      USD
2019-12-27  72.78  73.49  72.03  72.45  146372000      USD
2019-12-30  72.36  73.17  71.31  72.88  144238000      USD
2019-12-31  72.48  73.42  72.38  73.41  100991000      USD

Summary statistics:

              Open         High          Low        Close        Volume
count  2517.000000  2517.000000  2517.000000  2517.000000  2.517000e+03
mean     27.607346    27.851824    27.357636    27.613890  2.995842e+08
std      14.087225    14.208937    13.986766    14.108454  2.353177e+08
min       6.870000     7.000000     6.790000     6.860000  0.000000e+00
25%      16.250000    16.350000    16.050000    16.180000  1.245220e+08
50%      24.810000    25.080000    24.600000    24.880000  2.220309e+08
75%      37.620000    38.070000    37.300000    37.640000  4.068107e+08
max      96.950000    96.950000    96.950000    96.950000  1.880989e+09
shape=(2517, 6)

Null data:

Open        0
High        0
Low         0
Close       0
Volume      0
Currency    0
dtype: int64

## What if an input variable does not have a ticker? (eg. 10 year US bond yields)
The function above using ```get_stock_historical_data()``` will not work

- use a search function
```
investpy.search_quotes()
```

The search function is like using the search bar on investing.com and will let you find any quote that investing.com offers

__Note__
- ```countries``` parameter is the country flag that is shown on investing.coms website next to the instrument you want
- when ```n_results``` is 1, function will return the instrument instance/variable that we want. when it is more than one, function will return a list of "jibberish"

In [3]:
# What you would type into the search bar on 'investing.com'?
# 
# For US 10 year bond yields: "us 10 year", this will be used as the text parameter.


us10year = iv.search_quotes(text='us 10 year bond', products=['bonds'],
                                       countries=['united states'], n_results=1)

# check the quote that you found is the one that you want
print(us10year)

{"id_": 23705, "name": "United States 10-Year", "symbol": "US10YT=X", "country": "united states", "tag": "/rates-bonds/u.s.-10-year-bond-yield", "pair_type": "bonds", "exchange": "NYSE"}

Now use the ```retrieve_historical_data()``` function on ```us10year``` variable we created above

In [4]:
us10yeardata = us10year.retrieve_historical_data(from_date='1/1/1000', to_date=date.today().strftime('%d/%m/%Y'))

us10yeardata

             Open   High    Low  Close  Change Pct
Date
1988-02-22  8.245  8.245  8.245  8.245       -0.46
1988-02-23  8.171  8.171  8.171  8.171       -0.90
1988-02-24  8.175  8.175  8.175  8.175        0.05
1988-02-25  8.213  8.213  8.213  8.213        0.46
1988-02-26  8.180  8.180  8.180  8.180       -0.40
...           ...    ...    ...    ...         ...
2021-11-01  1.575  1.605  1.554  1.561       -1.00
2021-11-02  1.568  1.573  1.528  1.547       -0.90
2021-11-03  1.554  1.609  1.519  1.603        3.65
2021-11-04  1.593  1.609  1.509  1.530       -4.60
2021-11-05  1.545  1.552  1.436  1.455       -4.90

[9000 rows x 5 columns]

## Check variable types
use python builtin ```type()``` function

In [5]:
type(us10yeardata)

pandas.core.frame.DataFrame

## Technical Indicators offered in investpy package (we can use this metadata as inputs also!!!)
We still use the financial instrument stored in ```us10year``` variable above

use ```retrieve_technical_indicators()``` function

In [11]:
us10year_technical_data = us10year.retrieve_technical_indicators()

us10year_technical_data

              indicator     value           signal
0               RSI(14)   39.4350             sell
1            STOCH(9,6)   45.0350          neutral
2          STOCHRSI(14)    0.0000         oversold
3           MACD(12,26)    0.0060              buy
4               ADX(14)   30.9470          neutral
5           Williams %R  -92.9080         oversold
6               CCI(14) -174.6432             sell
7               ATR(14)    0.0650  high_volatility
8        Highs/Lows(14)   -0.1061             sell
9   Ultimate Oscillator   39.8730             sell
10                  ROC  -12.3720             sell
11  Bull/Bear Power(13)   -0.1316             sell

In [ ]:
type(us10year_technical_data)